name: quest_key
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  crystal_navigation_bar: ^1.0.4
  popup_card: ^0.1.0
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  flutter_local_notifications: ^19.1.0
  flutter_timezone: ^4.1.0
  timezone: ^0.10.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_assets/
    - assets/images/character_images/
    - assets/images/class_images/
